#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("OneKeyShareSample.Resource", IsApplication=true)]

namespace OneKeyShareSample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_launcher = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ssdk_auth_title_back = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ssdk_back_arr = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ssdk_logo = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ssdk_oks_classic_alipay = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ssdk_oks_classic_alipaymoments = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ssdk_oks_classic_bluetooth = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ssdk_oks_classic_check_checked = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ssdk_oks_classic_check_default = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ssdk_oks_classic_douban = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int ssdk_oks_classic_dropbox = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ssdk_oks_classic_email = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int ssdk_oks_classic_evernote = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int ssdk_oks_classic_facebook = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int ssdk_oks_classic_facebookmessenger = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int ssdk_oks_classic_flickr = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int ssdk_oks_classic_foursquare = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int ssdk_oks_classic_googleplus = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int ssdk_oks_classic_instagram = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int ssdk_oks_classic_instapaper = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int ssdk_oks_classic_kaixin = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int ssdk_oks_classic_kakaostory = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int ssdk_oks_classic_kakaotalk = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int ssdk_oks_classic_laiwang = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int ssdk_oks_classic_laiwangmoments = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int ssdk_oks_classic_line = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int ssdk_oks_classic_linkedin = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int ssdk_oks_classic_mingdao = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int ssdk_oks_classic_pinterest = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int ssdk_oks_classic_platform_cell_back = 2130837534;
			
			// aapt resource value: 0x7f020033
			public const int ssdk_oks_classic_platfrom_cell_back_nor = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int ssdk_oks_classic_platfrom_cell_back_sel = 2130837556;
			
			// aapt resource value: 0x7f02001f
			public const int ssdk_oks_classic_pocket = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int ssdk_oks_classic_progressbar = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int ssdk_oks_classic_qq = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int ssdk_oks_classic_qzone = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int ssdk_oks_classic_renren = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int ssdk_oks_classic_shortmessage = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int ssdk_oks_classic_sinaweibo = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int ssdk_oks_classic_tencentweibo = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int ssdk_oks_classic_tumblr = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int ssdk_oks_classic_twitter = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int ssdk_oks_classic_vkontakte = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int ssdk_oks_classic_wechat = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int ssdk_oks_classic_wechatfavorite = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int ssdk_oks_classic_wechatmoments = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int ssdk_oks_classic_whatsapp = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int ssdk_oks_classic_yixin = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int ssdk_oks_classic_yixinmoments = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int ssdk_oks_classic_youdao = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int ssdk_oks_ptr_ptr = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int ssdk_title_div = 2130837554;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050001
			public const int button1 = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int button2 = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int button3 = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int button4 = 2131034116;
			
			// aapt resource value: 0x7f050000
			public const int linearLayout1 = 2131034112;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_derect_share = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040057
			public const int app_btn1 = 2130968663;
			
			// aapt resource value: 0x7f040058
			public const int app_btn2 = 2130968664;
			
			// aapt resource value: 0x7f040059
			public const int app_btn3 = 2130968665;
			
			// aapt resource value: 0x7f04005a
			public const int app_btn4 = 2130968666;
			
			// aapt resource value: 0x7f04005b
			public const int app_derect_share = 2130968667;
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int ssdk_alipay = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int ssdk_alipay_client_inavailable = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int ssdk_alipaymoments = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int ssdk_bluetooth = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int ssdk_douban = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int ssdk_dropbox = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int ssdk_email = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int ssdk_evernote = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int ssdk_facebook = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int ssdk_facebookmessenger = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int ssdk_facebookmessenger_client_inavailable = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int ssdk_flickr = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int ssdk_foursquare = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int ssdk_google_plus_client_inavailable = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int ssdk_googleplus = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int ssdk_instagram = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int ssdk_instagram_client_inavailable = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int ssdk_instapager_email_or_password_incorrect = 2130968594;
			
			// aapt resource value: 0x7f04004a
			public const int ssdk_instapager_login_html = 2130968650;
			
			// aapt resource value: 0x7f040013
			public const int ssdk_instapaper = 2130968595;
			
			// aapt resource value: 0x7f040014
			public const int ssdk_instapaper_email = 2130968596;
			
			// aapt resource value: 0x7f040015
			public const int ssdk_instapaper_login = 2130968597;
			
			// aapt resource value: 0x7f040016
			public const int ssdk_instapaper_logining = 2130968598;
			
			// aapt resource value: 0x7f040017
			public const int ssdk_instapaper_pwd = 2130968599;
			
			// aapt resource value: 0x7f040018
			public const int ssdk_kaixin = 2130968600;
			
			// aapt resource value: 0x7f040019
			public const int ssdk_kakaostory = 2130968601;
			
			// aapt resource value: 0x7f04001a
			public const int ssdk_kakaostory_client_inavailable = 2130968602;
			
			// aapt resource value: 0x7f04001b
			public const int ssdk_kakaotalk = 2130968603;
			
			// aapt resource value: 0x7f04001c
			public const int ssdk_kakaotalk_client_inavailable = 2130968604;
			
			// aapt resource value: 0x7f04001d
			public const int ssdk_laiwang = 2130968605;
			
			// aapt resource value: 0x7f04001e
			public const int ssdk_laiwang_client_inavailable = 2130968606;
			
			// aapt resource value: 0x7f04001f
			public const int ssdk_laiwangmoments = 2130968607;
			
			// aapt resource value: 0x7f040020
			public const int ssdk_line = 2130968608;
			
			// aapt resource value: 0x7f040021
			public const int ssdk_line_client_inavailable = 2130968609;
			
			// aapt resource value: 0x7f040022
			public const int ssdk_linkedin = 2130968610;
			
			// aapt resource value: 0x7f040023
			public const int ssdk_mingdao = 2130968611;
			
			// aapt resource value: 0x7f040024
			public const int ssdk_mingdao_share_content = 2130968612;
			
			// aapt resource value: 0x7f040025
			public const int ssdk_neteasemicroblog = 2130968613;
			
			// aapt resource value: 0x7f04004b
			public const int ssdk_oks_cancel = 2130968651;
			
			// aapt resource value: 0x7f04004c
			public const int ssdk_oks_confirm = 2130968652;
			
			// aapt resource value: 0x7f04004d
			public const int ssdk_oks_contacts = 2130968653;
			
			// aapt resource value: 0x7f04004e
			public const int ssdk_oks_multi_share = 2130968654;
			
			// aapt resource value: 0x7f04004f
			public const int ssdk_oks_pull_to_refresh = 2130968655;
			
			// aapt resource value: 0x7f040050
			public const int ssdk_oks_refreshing = 2130968656;
			
			// aapt resource value: 0x7f040051
			public const int ssdk_oks_release_to_refresh = 2130968657;
			
			// aapt resource value: 0x7f040052
			public const int ssdk_oks_share = 2130968658;
			
			// aapt resource value: 0x7f040053
			public const int ssdk_oks_share_canceled = 2130968659;
			
			// aapt resource value: 0x7f040054
			public const int ssdk_oks_share_completed = 2130968660;
			
			// aapt resource value: 0x7f040055
			public const int ssdk_oks_share_failed = 2130968661;
			
			// aapt resource value: 0x7f040056
			public const int ssdk_oks_sharing = 2130968662;
			
			// aapt resource value: 0x7f040026
			public const int ssdk_pinterest = 2130968614;
			
			// aapt resource value: 0x7f040027
			public const int ssdk_pinterest_client_inavailable = 2130968615;
			
			// aapt resource value: 0x7f040028
			public const int ssdk_plurk = 2130968616;
			
			// aapt resource value: 0x7f040029
			public const int ssdk_pocket = 2130968617;
			
			// aapt resource value: 0x7f04002a
			public const int ssdk_qq = 2130968618;
			
			// aapt resource value: 0x7f04002b
			public const int ssdk_qq_client_inavailable = 2130968619;
			
			// aapt resource value: 0x7f04002c
			public const int ssdk_qzone = 2130968620;
			
			// aapt resource value: 0x7f04002d
			public const int ssdk_renren = 2130968621;
			
			// aapt resource value: 0x7f04002e
			public const int ssdk_share_to_facebook = 2130968622;
			
			// aapt resource value: 0x7f04002f
			public const int ssdk_share_to_googleplus = 2130968623;
			
			// aapt resource value: 0x7f040030
			public const int ssdk_share_to_mingdao = 2130968624;
			
			// aapt resource value: 0x7f040031
			public const int ssdk_share_to_qq = 2130968625;
			
			// aapt resource value: 0x7f040032
			public const int ssdk_share_to_qzone = 2130968626;
			
			// aapt resource value: 0x7f040033
			public const int ssdk_share_to_qzone_default = 2130968627;
			
			// aapt resource value: 0x7f040034
			public const int ssdk_shortmessage = 2130968628;
			
			// aapt resource value: 0x7f040035
			public const int ssdk_sinaweibo = 2130968629;
			
			// aapt resource value: 0x7f040036
			public const int ssdk_sohumicroblog = 2130968630;
			
			// aapt resource value: 0x7f040037
			public const int ssdk_sohusuishenkan = 2130968631;
			
			// aapt resource value: 0x7f040038
			public const int ssdk_tencentweibo = 2130968632;
			
			// aapt resource value: 0x7f040039
			public const int ssdk_tumblr = 2130968633;
			
			// aapt resource value: 0x7f04003a
			public const int ssdk_twitter = 2130968634;
			
			// aapt resource value: 0x7f04003b
			public const int ssdk_use_login_button = 2130968635;
			
			// aapt resource value: 0x7f04003c
			public const int ssdk_vkontakte = 2130968636;
			
			// aapt resource value: 0x7f04003d
			public const int ssdk_website = 2130968637;
			
			// aapt resource value: 0x7f04003e
			public const int ssdk_wechat = 2130968638;
			
			// aapt resource value: 0x7f04003f
			public const int ssdk_wechat_client_inavailable = 2130968639;
			
			// aapt resource value: 0x7f040040
			public const int ssdk_wechatfavorite = 2130968640;
			
			// aapt resource value: 0x7f040041
			public const int ssdk_wechatmoments = 2130968641;
			
			// aapt resource value: 0x7f040042
			public const int ssdk_weibo_oauth_regiseter = 2130968642;
			
			// aapt resource value: 0x7f040043
			public const int ssdk_weibo_upload_content = 2130968643;
			
			// aapt resource value: 0x7f040044
			public const int ssdk_whatsapp = 2130968644;
			
			// aapt resource value: 0x7f040045
			public const int ssdk_whatsapp_client_inavailable = 2130968645;
			
			// aapt resource value: 0x7f040046
			public const int ssdk_yixin = 2130968646;
			
			// aapt resource value: 0x7f040047
			public const int ssdk_yixin_client_inavailable = 2130968647;
			
			// aapt resource value: 0x7f040048
			public const int ssdk_yixinmoments = 2130968648;
			
			// aapt resource value: 0x7f040049
			public const int ssdk_youdao = 2130968649;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
